### PR TITLE
Add latitude and longitude in regencies table

### PR DESCRIPTION
**Pull request by kovloq**
Add latitude and longitude in regencies table.

The coordinate was taken from Google Map API. 
`https://maps.googleapis.com/maps/api/geocode/json?address=[nama kota/kabupaten]&region=id`

### CODE REVIEW

**Comment by edwardsamuel** [comment]
Hi Kovloq, 

Do you get the lat/lng information using script? If yes, it would be better if you could share your script.

**Comment by kovloq** [comment]
Hi Edward,

The lat/lng information was obtained using Google Geocode written in PHP script. I use limit when selecting a table to prevent timeout in PHP. 

[fecd0b0](https://github.com/edwardsamuel/Wilayah-Administratif-Indonesia/pull/5/commits/fecd0b05232cedd1d4c37b805ea68485ba4c8359)

The Geocode function provided by Google is not accurate enough. So, you need to find the lat/lng manually by using maps.google.com. Some of the cases are:
1. The information when obtained the information from "Kabupaten Bekasi" and "Kota Bekasi" are the same.
2.  Sometimes the function return blank. No lat/lng information is returned. 
More cases might be happen in other table as well. Those cases were only happened when I find the lat/lng in regencies table only.

**Comment by edwardsamuel** [comment]
Sorry for slow response. Have no free time for this project lately.

Hmm, the script can't be automated here and really hard to reproduce a new data. And also I think the lat/lng data may not be accurate here. What do you think?

**Comment by kovloq** [comment]
Yes, you right the lat/lng data is not accurate.
It's better not to merge this branch into master branch. Just leave the master branch like this is OK.

**Comment by int2k** [comment]
found this data 
[data.go.id](http://data.go.id/dataset/nama-kecamatan-dan-lokasinya)
but it quite old

**Comment by edwardsamuel** [comment]
@int2k As you said, the data is quite old. And looks like not up to date. 
If someone needs the latitude-longitude data, can consider the link above.

**Pull request closed without merging**
